project:
  type: website
  output-dir: docs

website:
  title: "Matthew Schoen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me! 
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
      - href: photos.qmd
        text: Photos 

format:
  html:
    theme: styles(V2).scss
    toc: true
    page-layout: full



